version: '3.8'

networks:
  mynetwork:
    driver: bridge

services:
  activemq:
    image: rmohr/activemq:latest
    hostname: activemq
    container_name: activemq
    ports:
      - "8161:8161"
      - "61613:61613"
    networks:
      - mynetwork
    environment:
      ACTIVEMQ_USERNAME: admin
      ACTIVEMQ_PASSWORD: admin
    volumes:
      - ./activemq-conf/activemq.xml:/opt/activemq/conf/activemq.xml

  celery_worker:
    build: .
    volumes:
      - .:/app
    depends_on:
      - activemq
    networks:
      - mynetwork
    environment:
      - ACTIVEMQ_HOST=activemq
      - ACTIVEMQ_PORT=61613
      - ACTIVEMQ_USERNAME=admin
      - ACTIVEMQ_PASSWORD=admin

  tester:
    build: .
    volumes:
      - .:/app
    depends_on:
      - celery_worker
    networks:
      - mynetwork
    command: python test_tasks.py
    environment:
      - ACTIVEMQ_HOST=activemq
      - ACTIVEMQ_PORT=61613
      - ACTIVEMQ_USERNAME=admin
      - ACTIVEMQ_PASSWORD=admin
