version: '3.8'

networks:
  mynetwork:
    driver: bridge

services:
  activemq:
    build:
      context: .
      dockerfile: Dockerfile.activemq
    hostname: activemq
    container_name: activemq
    ports:
      - "8161:8161"
      - "61613:61613"
      - "61616:61616"
    networks:
      - mynetwork
    environment:
      ACTIVEMQ_ADMIN_LOGIN: admin
      ACTIVEMQ_ADMIN_PASSWORD: admin
      ACTIVEMQ_WEBADMIN_PORT: 8161

  celery_worker:
    build: .
    volumes:
      - .:/app
    depends_on:
      - activemq
    networks:
      - mynetwork
    environment:
      - ACTIVEMQ_HOST=activemq
      - ACTIVEMQ_PORT=61613
      - ACTIVEMQ_USERNAME=admin
      - ACTIVEMQ_PASSWORD=admin
