version: '3.8'

services:
  redis-node-1:
    image: redis:6.2
    command: redis-server --port 7000 --cluster-enabled yes --cluster-config-file nodes.conf --cluster-node-timeout 5000 --appendonly yes
    ports:
      - 7000:7000
    networks:
      redis-net:
        ipv4_address: 172.28.0.2
    volumes:
      - redis-node-1-data:/data

  redis-node-2:
    image: redis:6.2
    command: redis-server --port 7001 --cluster-enabled yes --cluster-config-file nodes.conf --cluster-node-timeout 5000 --appendonly yes
    ports:
      - 7001:7001
    networks:
      redis-net:
        ipv4_address: 172.28.0.3
    volumes:
      - redis-node-2-data:/data

  redis-node-3:
    image: redis:6.2
    command: redis-server --port 7002 --cluster-enabled yes --cluster-config-file nodes.conf --cluster-node-timeout 5000 --appendonly yes
    ports:
      - 7002:7002
    networks:
      redis-net:
        ipv4_address: 172.28.0.4
    volumes:
      - redis-node-3-data:/data

  redis-node-4:
    image: redis:6.2
    command: redis-server --port 7003 --cluster-enabled yes --cluster-config-file nodes.conf --cluster-node-timeout 5000 --appendonly yes
    ports:
      - 7003:7003
    networks:
      redis-net:
        ipv4_address: 172.28.0.5
    volumes:
      - redis-node-4-data:/data

  redis-node-5:
    image: redis:6.2
    command: redis-server --port 7004 --cluster-enabled yes --cluster-config-file nodes.conf --cluster-node-timeout 5000 --appendonly yes
    ports:
      - 7004:7004
    networks:
      redis-net:
        ipv4_address: 172.28.0.6
    volumes:
      - redis-node-5-data:/data

  redis-node-6:
    image: redis:6.2
    command: redis-server --port 7005 --cluster-enabled yes --cluster-config-file nodes.conf --cluster-node-timeout 5000 --appendonly yes
    ports:
      - 7005:7005
    networks:
      redis-net:
        ipv4_address: 172.28.0.7
    volumes:
      - redis-node-6-data:/data

  redis-setup:
    image: redis:6.2
    depends_on:
      - redis-node-1
      - redis-node-2
      - redis-node-3
      - redis-node-4
      - redis-node-5
      - redis-node-6
    networks:
      redis-net:
        ipv4_address: 172.28.0.8
    entrypoint: >
      sh -c "
      sleep 20;
      echo 'yes' | redis-cli --cluster create
      172.28.0.2:7000
      172.28.0.3:7001
      172.28.0.4:7002
      172.28.0.5:7003
      172.28.0.6:7004
      172.28.0.7:7005
      --cluster-replicas 1;
      redis-cli -h 172.28.0.2 -p 7000 cluster info;
      "

  twemproxy:
    build:
      context: .
      dockerfile: Dockerfile.twemproxy
    ports:
      - 22122:22122
    networks:
      redis-net:
        ipv4_address: 172.28.0.9
    volumes:
      - ./twemproxy/nutcracker.yml:/etc/nutcracker/nutcracker.yml

  celery:
    build: .
    command: celery -A tasks worker --loglevel=info
    volumes:
      - .:/app
    depends_on:
      - redis-setup
      - twemproxy
    networks:
      - redis-net

  celery-beat:
    build: .
    command: celery -A tasks beat --loglevel=info
    volumes:
      - .:/app
    depends_on:
      - redis-setup
      - twemproxy
    networks:
      - redis-net

networks:
  redis-net:
    driver: bridge
    ipam:
      config:
        - subnet: 172.28.0.0/16

volumes:
  redis-node-1-data:
  redis-node-2-data:
  redis-node-3-data:
  redis-node-4-data:
  redis-node-5-data:
  redis-node-6-data:
