version: '3.8'

services:
  activemq:
    build: .
    ports:
      - "61616:61616"
      - "8161:8161"
      - "61613:61613"
    volumes:
      - ./activemq.xml:/opt/activemq/conf/activemq.xml
      - ./log4j.properties:/opt/activemq/conf/log4j.properties
